### ISSUE TITLE
module not found: com.cgnal.spark#spark-opentsdb_2.10

### ISSUE THREAD

**Issue by mk-qi** [CGnal/spark-openTSDB-example#2]
hello , as described  by the title . like below 

> [info] Resolving com.cgnal.spark#spark-opentsdb_2.10;1.0 ...
> [warn]  module not found: com.cgnal.spark#spark-opentsdb_2.10;1.0

**Comment by fabiana001** [comment]
HI!
I'm sorry for the delay in answering.
The library spark-opentsdb is a private low-level Api used to write/read DataPoint collections (e.g., DStream, RDD, DataFrame) into/from OpenTSDB without using the HTTP API provided by OpenTSDB.
We are thinking to release soon a public version of this library. In the while you can remove that dependency and substitute the method [streamWrite(stream)](https://github.com/CGnal/spark-openTSDB-example/blob/master/src/main/scala/com/cgnal/kafkaAvro/consumers/OpenTSDBConsumer.scala)
with an [http put request](http://opentsdb.net/docs/build/html/api_http/put.html).

**Comment by devaudio** [comment]
well that's no fun. I just ran into that too :(
sbt.ResolveException: unresolved dependency: com.cgnal.spark#spark-opentsdb_2.10;1.0: not found

Are there plans to release it soon, still?

**Comment by asavartsov** [comment]
Such an inspiring article about thing that not exist...

**Comment by dgreco** [comment]
I understand the point, we are still evaluating the possibility to make that library open source. Sorry about that.

**Comment by dgreco** [comment]
Hello all, I made public the spark-opentsdb project so now you could make it running the example, just in case.

**Comment by asavartsov** [comment]
Wow, @dgreco! Thanks for sharing!

**Comment by dgreco** [comment]
You're welcome, any feedback would be very welcome ;)
